name = "SimpleCC"
uuid = "b67096f2-cb5c-4e65-ab3c-44150b6abefa"
authors = ["James Schloss <jrs.schloss@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
